supergraph:
  listen: 127.0.0.1:4000

headers:
  all:
    request:
      - propagate:
          matching: .*

include_subgraph_errors:
  all: true
telemetry:
  apollo:
    errors:
      subgraph:
        all:
          send: true
          redact: false
