supergraph:
  listen: 127.0.0.1:4000

headers:
  all:
    request:
      - propagate:
          matching: .*

telemetry:
  apollo:
    field_level_instrumentation_sampler: 1
    errors:
      subgraph:
        all:
          send: true
          redact: false

  instrumentation:
    spans:
      mode: spec_compliant


