name: pr-check-code

on: pull_request

env:
  APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}

jobs:
  npm-build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - run: npm ci

      - run: npm test

  schema-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Check flights subgraph
        run: |
          rover subgraph check apollo-travel-supergraph@prod \
            --name flights \
            --schema ./subgraphs/flights/schema.graphql

      - name: Check hotels subgraph
        run: |
          rover subgraph check apollo-travel-supergraph@prod \
            --name hotels \
            --schema ./subgraphs/hotels/schema.graphql

      - name: Check users subgraph
        run: |
          rover subgraph check apollo-travel-supergraph@prod \
            --name users \
            --schema ./subgraphs/users/schema.graphql
