name: pr-check-code

on: pull_request

env:
  APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
  APOLLO_GRAPH_REF: "apollo-travel-supergraph@prod"

jobs:
  npm-build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "npm"

      - uses: apollosolutions/rover-actions/install-rover-cli@v1

      - run: npm ci

      - run: npm test

  schema-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: apollosolutions/rover-actions/install-rover-cli@v1

      - name: Check flights subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ env.APOLLO_GRAPH_REF }}
          name: flights
          schema: ./subgraphs/flights/schema.graphql

      - name: Check hotels subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ env.APOLLO_GRAPH_REF }}
          name: hotels
          schema: ./subgraphs/hotels/schema.graphql

      - name: Check suggestions subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ env.APOLLO_GRAPH_REF }}
          name: suggestions
          schema: ./subgraphs/suggestions/schema.graphql

      - name: Check trips subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ env.APOLLO_GRAPH_REF }}
          name: trips
          schema: ./subgraphs/trips/schema.graphql

      - name: Check users subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ env.APOLLO_GRAPH_REF }}
          name: users
          schema: ./subgraphs/users/schema.graphql
